# These have to be manually defined because PAR comes after the tracers, otherwise we could write `whatever(::Val(...), x, y, z, t, NO₃, ..., args...)` etc.

# core fallback
@inline (bgc::LOBSTER)(tracer::Val{:NO₃}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::Val{:NH₄}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::Val{:P}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::Val{:Z}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::sPOM, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(Val(:sPOM), x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::bPOM, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(Val(:bPOM), x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::DOM, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(Val(:DOM), x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::SRDOM, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(Val(:SRDOM), x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])
@inline (bgc::LOBSTER)(tracer::RDOM, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args...) = @inbounds bgc(Val(:RDOM), x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, args[end])

# Carbonates and oxygen
# We can't tell the difference between carbonates and oxygen, and variable redfields without specifying more 
# We're lucky that the optional groups have 2, 1, 3 extra variables each so this is the only non-unique combination
@inline (bgc::LOBSTER{<:Any, <:Val{(true, true, false)}, <:Any})(tracer::Val{:DIC}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, DIC, Alk, O₂, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, DIC, Alk, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, true, false)}, <:Any})(tracer::Val{:Alk}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, DIC, Alk, O₂, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, DIC, Alk, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, true, false)}, <:Any})(tracer::Val{:O₂}, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, DIC, Alk, O₂, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOM, bPOM, DOM, SRDOM, RDOM, O₂, PAR)

# Carbonates and variable redfield
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(tracer::Val{:DIC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOC / bgc. organic_redfield, bPOC / bgc. organic_redfield, DOC / bgc. organic_redfield, SRDOC / bgc. organic_redfield, RDOC / bgc. organic_redfield, DIC, Alk, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(tracer::Val{:Alk}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOC / bgc. organic_redfield, bPOC / bgc. organic_redfield, DOC / bgc. organic_redfield, SRDOC / bgc. organic_redfield, RDOC / bgc. organic_redfield, DIC, Alk, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(tracer::Val{:sPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(tracer::Val{:bPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(::Val{:DOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:DOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(::Val{:SRDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:SRDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(true, false, true)}, <:Any})(::Val{:RDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:RDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)

# Oxygen and variable redfield
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(tracer::Val{:O₂}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(tracer::Val{:sPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(tracer::Val{:bPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(::Val{:DOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:DOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(::Val{:SRDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:SRDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER{<:Any, <:Val{(false, true, true)}, <:Any})(::Val{:RDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:RDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)

# Carbonates, oxygen, and variable redfield
@inline (bgc::LOBSTER)(tracer::Val{:DIC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOC / bgc. organic_redfield, bPOC / bgc. organic_redfield, DOC / bgc. organic_redfield, SRDOC / bgc. organic_redfield, RDOC / bgc. organic_redfield, DIC, Alk, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:Alk}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPOC / bgc. organic_redfield, bPOC / bgc. organic_redfield, DOC / bgc. organic_redfield, SRDOC / bgc. organic_redfield, RDOC / bgc. organic_redfield, DIC, Alk, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:O₂}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, O₂, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:sPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:bPOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(tracer, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:DOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:DOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:SRDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:SRDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
@inline (bgc::LOBSTER)(tracer::Val{:RDOC}, x, y, z, t, NO₃, NH₄, P, Z, sPON, bPON, DON, SRDON, RDON, DIC, Alk, O₂, sPOC, bPOC, DOC, SRDOC, RDOC, PAR) = bgc(Val(:RDOM), x, y, z, t, NO₃, NH₄, P * bgc.phytoplankton_redfield, Z * bgc.phytoplankton_redfield, sPOC, bPOC, DOC, SRDOC, RDOC, PAR)
